export const SAVE_USERDATA = "SAVE_USERDATA";
export const CHANGE_USERNAME = "CHANGE_USERNAME";
export const RESET = "RESET";

export const GET_ACCESS_TOKEN = "GET_ACCESS_TOKEN";

export const POST_LOADING_TRUE = "POST_LOADING_TRUE";
export const POST_LOADING_FALSE = "POST_LOADING_FALSE";
export const SAVE_POST = "SAVE_POST";
export const POST_ERROR_TRUE = "POST_ERROR_TRUE";
export const POST_ERROR_FALSE = "POST_ERROR_FALSE";
export const NUMBER_OF_POSTS = "NUMBER_OF_POSTS";

export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";

export const NEW_FOLLOWER = "NEW_FOLLOWER";
export const REMOVE_FOLLOWER = "REMOVE_FOLLOWER";
export const NEW_FOLLOWING = "NEW_FOLLOWING";
export const REMOVE_FOLLOWING = "REMOVE_FOLLOWING";

export const VIEW_ACCOUNT = "VIEW_ACCOUNT";

export const SAVE_ALL_NOTIFICATIONS = "SAVE_ALL_NOTIFICATIONS";
export const SAVE_NOTIFICATION = "SAVE_NOTIFICATION";
export const REMOVE_NOTIFICATIONS = "REMOVE_NOTIFICATIONS";

export const SAVE_PERSONALCHAT_USER_DATA = "SAVE_PERSONALCHAT_USER_DATA";

export const SHOW_POST = "SHOW_POST";
